[package]
name = "wgpu-matrix-simple"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytemuck = { version = "1.23.0", features = ["derive"] }
tokio = { version = "1.45.1", features = ["full"] }
wgpu = "25.0.2"
